server:
  port: 8080
  servlet:
    context-path: /petshop

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

petshop:
  jwt:
    expiracao: 7200000
    segredo: "igorshimauti"